version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/flashcards
    depends_on:
      - mongodb
    networks:
      - flashcards-network

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: flashcards
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - flashcards-network

volumes:
  mongodb_data:

networks:
  flashcards-network:
    driver: bridge
